config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resource :session
  resources :passwords, param: :token
  resources :users
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "users#frontpage"
  get "swipe", to: "people#swipe", as: :swipe
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy!

    respond_to do |format|
      format.html { redirect_to profiles_path, notice: "Profile was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.fetch(:profile, {})
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.slim
= form_with(model: profile) do |form|
  - if profile.errors.any?
    div style="color: red"
      h2 = "#{pluralize(profile.errors.count, "error")} prohibited this profile from being saved:"
      ul
        - profile.errors.each do |error|
          li = error.full_message

  div
    = form.submit

app/views/profiles/_profile.html.slim
div id="#{dom_id profile}"

app/views/profiles/edit.html.slim
h1 Editing profile

== render "form", profile: @profile

br

div
  => link_to "Show this profile", @profile
  '|
  =< link_to "Back to profiles", profiles_path

app/views/profiles/index.html.slim
p style="color: green" = notice

h1 Profiles

#profiles
  - @profiles.each do |profile|
    == render profile
    p
      = link_to "Show this profile", profile

= link_to "New profile", new_profile_path

app/views/profiles/new.html.slim
h1 New profile

== render "form", profile: @profile

br

div
  = link_to "Back to profiles", profiles_path

app/views/profiles/show.html.slim
p style="color: green" = notice

== render @profile

div
  => link_to "Edit this profile", edit_profile_path(@profile)
  '|
  =< link_to "Back to profiles", profiles_path

  = button_to "Destroy this profile", @profile, method: :delete