config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resource :session
  resources :passwords, param: :token
  resources :users
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "users#frontpage"
  get "swipe", to: "people#swipe", as: :swipe
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]

  def swipe
  end

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_path, notice: "Person was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.expect(person: [:name, :gender])
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.slim
= form_with(model: person) do |form|
  - if person.errors.any?
    div style="color: red"
      h2 = "#{pluralize(person.errors.count, "error")} prohibited this person from being saved:"
      ul
        - person.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :gender, style: "display: block"
    = form.text_field :gender

  div
    = form.submit

app/views/people/_person.html.slim
div id="#{dom_id person}"
  p
    strong Name:
    =< person.name
  p
    strong Gender:
    =< person.gender

app/views/people/edit.html.slim
h1 Editing person

== render "form", person: @person

br

div
  => link_to "Show this person", @person
  '|
  =< link_to "Back to people", people_path

app/views/people/index.html.slim
p style="color: green" = notice

h1 People

#people
  - @people.each do |person|
    == render person
    p
      = link_to "Show this person", person

= link_to "New person", new_person_path

<button class="btn btn-primary">Hello daisyUI!</button>

app/views/people/new.html.slim
h1 New person

== render "form", person: @person

br

div
  = link_to "Back to people", people_path

app/views/people/show.html.slim
p style="color: green" = notice

== render @person

div
  => link_to "Edit this person", edit_person_path(@person)
  '|
  =< link_to "Back to people", people_path

  = button_to "Destroy this person", @person, method: :delete

app/views/people/swipe.html.slim
css:
  *, *:before, *:after {
    box-sizing: border-box;
    padding: 0;
    margin: 0;
  }
  body {
    overflow: hidden;
    font-family: sans-serif;
  }
  .tinder {
    width: 100vw;
    height: 100vh;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    position: relative;
    opacity: 0;
    transition: opacity 0.1s ease-in-out;
  }
  .loaded.tinder {
    opacity: 1;
  }
  .tinder--status {
    position: absolute;
    top: 50%;
    margin-top: -30px;
    z-index: 2;
    width: 100%;
    text-align: center;
    pointer-events: none;
  }
  .tinder--status i {
    font-size: 100px;
    opacity: 0;
    transform: scale(0.3);
    transition: all 0.2s ease-in-out;
    position: absolute;
    width: 100px;
    margin-left: -50px;
  }
  .tinder_love .fa-heart {
    opacity: 0.7;
    transform: scale(1);
  }
  .tinder_nope .fa-times {
    opacity: 0.7;
    transform: scale(1);
  }
  .fa-heart {
    color: #FFACE4;
  }
  .fa-remove {
    color: #CDD6DD;
  }
  .tinder--cards {
  }
  .tinder--card {
    display: inline-block;
    width: 90vw;
    max-width: 400px;
    height: 70vh;
    padding-bottom: 40px;
    border-radius: 8px;
    overflow: hidden;
    position: absolute;
    will-change: transform;
    transition: all 0.3s ease-in-out;
    cursor: -webkit-grab;
    cursor: -moz-grab;
    cursor: grab;
  }
  .moving.tinder--card {
    transition: none;
    cursor: -webkit-grabbing;
    cursor: -moz-grabbing;
    cursor: grabbing;
  }
  .tinder--card img {
    max-width: 100%;
    pointer-events: none;
  }
  .tinder--card h3 {
    pointer-events: none;
  }
  .tinder--card p {
    pointer-events: none;
  }
  .tinder--buttons {
    flex: 0 0 100px;
    text-align: center;
    padding-top: 20px;
  }
  .tinder--buttons button {
    border-radius: 50%;
    line-height: 60px;
    width: 60px;
    border: 0;
    background: #FFFFFF;
    display: inline-block;
    margin: 0 8px;
  }
  .tinder--buttons button:focus {
    outline: 0;
  }
  .tinder--buttons i {
    font-size: 32px;
    vertical-align: middle;
  }
  

.tinder data-controller="swipe"
  .tinder--status
    i.fa.fa-remove
    i.fa.fa-heart
  .tinder--cards.flex.justify-center
    .tinder--card.bg-zinc-100
      .flex-col
        .carousel.carousel-vertical.rounded-box.h-96.w-full
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1559703248-dcaaec9fab78.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1565098772267-60af42b81ef2.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1572635148818-ef6fd45eb394.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1494253109108-2e30c049369b.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1550258987-190a2d41a8ba.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1559181567-c3190ca9959b.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1601004890684-d8cbf643f5f2.webp"
      h3.text-zinc-800 Bob
      p.text-zinc-800 This is a demo for Tinder like swipe cards
    .tinder--card.bg-zinc-100
      .flex-col
        .carousel.carousel-vertical.rounded-box.h-96.w-full
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1559703248-dcaaec9fab78.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1565098772267-60af42b81ef2.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1572635148818-ef6fd45eb394.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1494253109108-2e30c049369b.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1550258987-190a2d41a8ba.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1559181567-c3190ca9959b.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1601004890684-d8cbf643f5f2.webp"

      h3.text-zinc-800 Bobette
      p.text-zinc-800 This is a demo for Tinder like swipe cards
    .tinder--card.bg-zinc-100
      .flex-col
        .carousel.carousel-vertical.rounded-box.h-96.w-full
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1559703248-dcaaec9fab78.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1565098772267-60af42b81ef2.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1572635148818-ef6fd45eb394.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1494253109108-2e30c049369b.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1550258987-190a2d41a8ba.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1559181567-c3190ca9959b.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1601004890684-d8cbf643f5f2.webp"

      h3.text-zinc-800 Bobby
      p.text-zinc-800 This is a demo for Tinder like swipe cards
    .tinder--card.bg-zinc-100
      .flex-col
        .carousel.carousel-vertical.rounded-box.h-96.w-full
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1559703248-dcaaec9fab78.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1565098772267-60af42b81ef2.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1572635148818-ef6fd45eb394.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1494253109108-2e30c049369b.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1550258987-190a2d41a8ba.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1559181567-c3190ca9959b.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1601004890684-d8cbf643f5f2.webp"

      h3.text-zinc-800 Labobo
      p.text-zinc-800 This is a demo for Tinder like swipe cards
    .tinder--card.bg-zinc-100
      .flex-col
        .carousel.carousel-vertical.rounded-box.h-96.w-full
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1559703248-dcaaec9fab78.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1565098772267-60af42b81ef2.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1572635148818-ef6fd45eb394.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1494253109108-2e30c049369b.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1550258987-190a2d41a8ba.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1559181567-c3190ca9959b.webp"
          .carousel-item.w-full.h-full
            img.w-full.object-cover src="https://img.daisyui.com/images/stock/photo-1601004890684-d8cbf643f5f2.webp"

      h3.text-zinc-800 Bob the Bob
      p.text-zinc-800 This is a demo for Tinder like swipe cards

<div class="tinder--buttons">
  <button id="nope"><i class="fa fa-remove"></i></button>
  <button id="love"><i class="fa fa-heart"></i></button>
</div>