config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resource :session
  resources :passwords, param: :token
  resources :users
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "users#frontpage"
  get "swipe", to: "people#swipe", as: :swipe
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  allow_unauthenticated_access only: %i[new create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        start_new_session_for @user
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        flash[:alert] = @user.errors.full_messages.join("\n")
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
.flex.flex-col.items-center.justify-center.min-h-screen.-my-8
  = form_with(model: user) do |form|
    - if user.errors.any?
      div style="color: red"
        h2 = "#{pluralize(user.errors.count, "error")} prohibited this user from being saved:"
        ul
          - user.errors.each do |error|
            li = error.full_message

    fieldset.fieldset.bg-base-200.border-base-300.rounded-box.w-xs.border.p-4
      legend Sign up
      .field
        = form.label :email_address, class: "label"
        = form.email_field :email_address, required: true, autofocus: true, value: params[:email_address], class: "input", placeholder: "Enter your email"
      .field-group
        .field
          = form.label :password, class: "label"
          = form.password_field :password, required: true, placeholder: "Enter your password", maxlength: 72, class: "input"
        .field
          = form.label :password_confirmation, class: "label"
          = form.password_field :password_confirmation, required: true, placeholder: "Confirm your password", maxlength: 72, class: "input"
      .field
        = form.submit "Sign up", class: "btn btn-primary"

app/views/users/_user.html.slim
div id="#{dom_id user}"

app/views/users/edit.html.slim
h1 Editing user

== render "form", user: @user

br

div
  => link_to "Show this user", @user
  '|
  =< link_to "Back to users", users_path

app/views/users/frontpage.html.slim
= link_to "Swipe", swipe_path, class: "btn btn-primary"
<button class="btn btn-primary">Settings</button>
<button class="btn btn-primary">Profile</button>
<i class="fa fa-heart" style="color: #FFACE4;">

app/views/users/index.html.slim
p style="color: green" = notice

h1 Users

#users
  - @users.each do |user|
    == render user
    p
      = link_to "Show this user", user

= link_to "New user", new_user_path

app/views/users/new.html.slim
== render "form", user: @user

br

app/views/users/show.html.slim
p style="color: green" = notice

== render @user

div
  => link_to "Edit this user", edit_user_path(@user)
  '|
  =< link_to "Back to users", users_path

  = button_to "Destroy this user", @user, method: :delete